[package]
name = "mpo_lab1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
num_cpus = "1.15.0"
rand = "0.8.5"
